import NextHead from "next/head"

interface Props {}

export default function Head({}: Props): JSX.Element {
  return (
    <NextHead>
      <title>Matilda Price</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </NextHead>
  )
}
