import type { NextPage } from "next"
import Head from "next/head"
import NextImage from "next/image"
import Gallery from "../components/Gallery"
import styles from "../styles/Home.module.css"

const PORTFOLIO_IMAGES = [
  {
    id: "1",
    src: "https://www.c-heads.com/wp-content/uploads/2019/11/26-1.jpg",
    alt: "Matilda Price",
  },
  {
    id: "2",
    src: "https://www.c-heads.com/wp-content/uploads/2019/11/22.jpg",
    alt: "Matilda Price",
  },
  {
    id: "3",
    src: "https://onemanagement.com/assets/2019-06-03-comps/composite_92485.png",
    alt: "Matilda Price",
  },
]

function Project() {
  return (
    <section className="project">
      <div className="project-content">
        <Gallery images={PORTFOLIO_IMAGES} />
      </div>
    </section>
  )
}

function About() {
  return (
    <section style={{ left: 0, top: 15, position: "fixed" }}>
      <div className="about-inner">
        <div className="about-inner__service">
          <h1 style={{ marginBottom: 30 }}>Matilda Price</h1>
          <ul style={{ display: "flex" }}>
            <li style={{ marginRight: 10 }}>
              <a
                href="https://www.instagram.com/matildajoprice"
                target="_blank"
              >
                <NextImage src="/logos/instagram.webp" width="40" height="40" />
              </a>
            </li>
            <li>
              <a href="https://www.imdb.com/name/nm11361521" target="_blank">
                <NextImage src="/logos/imdb.png" width="40" height="40" />
              </a>
            </li>
          </ul>
        </div>
      </div>
    </section>
  )
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Matilda Price</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <About />
        <Project />
      </main>
    </div>
  )
}

export default Home
